// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Article struct {
	ID             int64
	Title          sql.NullString
	Url            sql.NullString
	SourceName     sql.NullString
	PublishedDate  sql.NullTime
	Summary        sql.NullString
	Entities       interface{}
	ContentType    sql.NullString
	Topics         interface{}
	Status         sql.NullString
	AnalysisStatus sql.NullString
	StoryGroupID   sql.NullString
	Content        sql.NullString
}
