// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    title,
    url,
    source_name,
    published_date,
    summary,
    entities,
    content_type,
    topics,
    status,
    story_group_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, title, url, source_name, published_date, summary, entities, content_type, topics, status, story_group_id
`

type CreateArticleParams struct {
	Title         sql.NullString
	Url           sql.NullString
	SourceName    sql.NullString
	PublishedDate sql.NullTime
	Summary       sql.NullString
	Entities      interface{}
	ContentType   sql.NullString
	Topics        interface{}
	Status        sql.NullString
	StoryGroupID  sql.NullString
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Url,
		arg.SourceName,
		arg.PublishedDate,
		arg.Summary,
		arg.Entities,
		arg.ContentType,
		arg.Topics,
		arg.Status,
		arg.StoryGroupID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.SourceName,
		&i.PublishedDate,
		&i.Summary,
		&i.Entities,
		&i.ContentType,
		&i.Topics,
		&i.Status,
		&i.StoryGroupID,
	)
	return i, err
}

const getArticleByUrl = `-- name: GetArticleByUrl :one
SELECT id, title, url, source_name, published_date, summary, entities, content_type, topics, status, story_group_id FROM articles WHERE url = ? LIMIT 1
`

func (q *Queries) GetArticleByUrl(ctx context.Context, url sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByUrl, url)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.SourceName,
		&i.PublishedDate,
		&i.Summary,
		&i.Entities,
		&i.ContentType,
		&i.Topics,
		&i.Status,
		&i.StoryGroupID,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, url, source_name, published_date, summary, entities, content_type, topics, status, story_group_id FROM articles
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.SourceName,
			&i.PublishedDate,
			&i.Summary,
			&i.Entities,
			&i.ContentType,
			&i.Topics,
			&i.Status,
			&i.StoryGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
