dsn: "./ai-news.db"
sources:
  - name: "Ars Technica AI"
    url: "http://feeds.arstechnica.com/arstechnica/technology-lab"
    type: "rss"
    priority: 2
  - name: "Hugging Face Blog"
    url: "https://huggingface.co/blog/feed.xml"
    type: "rss"
    priority: 1
  - name: "OpenAI Blog"
    url: "https://openai.com/blog/rss.xml"
    type: "rss"
    priority: 1
