dsn: "./ai-news.db"

ai:
  # Available models: gemini-1.5-flash, gemini-1.5-pro, gemini-2.5-flash, gemini-2.5-pro, etc.
  # For full list, see: https://ai.google.dev/gemini-api/docs/models/gemini
  gemini_model: "gemini-1.5-flash"

sources:
  - name: "Hugging Face Blog"
    url: "https://huggingface.co/blog/feed.xml"
    type: "rss"
    priority: 1
  - name: "OpenAI Blog"
    url: "https://openai.com/blog/rss.xml"
    type: "rss"
    priority: 1
